import type { LiveEvent, TimedEvent } from './events.js'

/** Offline playback of the double-dip war room, so the exhibit can be built and demoed without live agents. */
export function doubleDipReplay(): TimedEvent[] {
  const case_id = 'case_replay_doubledip'
  const order_id = 'ord_doubledip'
  const seq: [number, LiveEvent][] = [
    [0, { type: 'hello', server_time: '2026-10-03T16:00:00.000Z', active_case: null, merchant: 'Harbor & Pine Outfitters' }],
    [800, { type: 'case.opened', case_id, kind: 'dispute', order_id, customer_id: 'cus_doubledip', customer_name: 'Theo Walsh', title: 'Chargeback dp_doubledip · Visa 10.4 fraudulent · $289.00', summary: 'Cardholder says: "I did not make this purchase. An AI assistant on my phone placed it without my approval." A return on this order was already refunded.', amount: 289, population: 'undeclared-suspected', flags: ['undeclared_agent', 'double_dip', 'refund_on_first_scan', 'agent_did_it_claim'], room: { id: 'room_replay', title: 'Dispute War Room' }, due_by: '2026-10-08T16:00:00.000Z' }],
    [1600, { type: 'agent.joined', case_id, agent: 'critic', handle: 'critic-agent' }],
    [1900, { type: 'agent.message', case_id, agent: 'critic', text: 'New dispute on ord_doubledip. @history pull the customer record, @identity classify the session, @logistics trace the return, @forensics check the claim.', mentions: ['history', 'identity', 'logistics', 'forensics'] }],
    [2200, { type: 'agent.joined', case_id, agent: 'history', handle: 'history-agent' }],
    [2300, { type: 'agent.joined', case_id, agent: 'identity', handle: 'identity-agent' }],
    [2400, { type: 'agent.joined', case_id, agent: 'logistics', handle: 'logistics-agent' }],
    [2500, { type: 'agent.joined', case_id, agent: 'forensics', handle: 'forensics-agent' }],
    [2600, { type: 'agent.status', case_id, agent: 'history', status: 'tool', detail: 'get_customer_history(cus_doubledip)' }],
    [2700, { type: 'agent.status', case_id, agent: 'identity', status: 'tool', detail: 'classify_session(ord_doubledip)' }],
    [2800, { type: 'agent.status', case_id, agent: 'logistics', status: 'tool', detail: 'trace_return(ret_doubledip)' }],
    [2900, { type: 'agent.status', case_id, agent: 'forensics', status: 'tool', detail: 'inspect_claim(dp_doubledip)' }],
    [4200, { type: 'evidence.attached', case_id, agent: 'identity', evidence: { id: 'ev_fp', family: 'agent_identity', label: 'Shared sandbox fingerprint', detail: 'Fingerprint fp_7c1e9a_linux-chrome131-swiftshader-2vcpu is shared by 37 sessions across different customers. This is an agent sandbox image, not a customer device.', severity: 'critical', weight: 0.45, node_ids: [order_id, 'dev_muse'], graph: { nodes: [{ id: 'dev_muse', type: 'device', label: 'muse-sandbox', population: 'cluster' }], edges: [{ source: order_id, target: 'dev_muse', type: 'used_device' }] } } }],
    [4600, { type: 'evidence.attached', case_id, agent: 'identity', evidence: { id: 'ev_egress', family: 'agent_identity', label: 'Cloud egress, no signature', detail: 'Purchase IP egresses from Cloudflare (AS13335). No Signature-Agent header, no Web Bot Auth signature, no Visa TAP token. Population: undeclared-suspected (score 1.0).', severity: 'suspicious', weight: 0.2, node_ids: [order_id] } }],
    [5000, { type: 'agent.message', case_id, agent: 'identity', text: 'Session was an undeclared agent: Muse-style sandbox, zero pointer telemetry, 52 s session, fresh single-use Link card. No CE 3.0 device evidence exists for this customer. @critic', mentions: ['critic'] }],
    [5600, { type: 'evidence.attached', case_id, agent: 'history', evidence: { id: 'ev_hist', family: 'customer_history', label: 'Account 16 days old, first order', detail: 'cus_doubledip created 16 days ago. One order, one return, one dispute. No prior undisputed transactions in the 120 to 365 day window.', severity: 'suspicious', weight: 0.15, node_ids: ['cus_doubledip', order_id] } }],
    [6000, { type: 'agent.message', case_id, agent: 'history', text: 'No history to lean on. First order, already returned, now disputed. @critic', mentions: ['critic'] }],
    [6800, { type: 'evidence.attached', case_id, agent: 'logistics', evidence: { id: 'ev_delivery', family: 'delivery', label: 'Delivered with carrier scan', detail: 'FedEx delivered to the order address, scan proof on file, address matches billing.', severity: 'exculpatory', weight: -0.2, node_ids: [order_id] } }],
    [7300, { type: 'evidence.attached', case_id, agent: 'logistics', evidence: { id: 'ev_refund', family: 'double_dip', label: 'Refund already issued on first scan', detail: 'ret_doubledip refunded $289.00 three minutes after the carrier\'s first inbound scan (trigger: carrier_scan). The parcel later weighed 1,010 g against 980 g expected, so the item came back.', severity: 'critical', weight: 0.5, node_ids: [order_id, 'ret_doubledip'] } }],
    [7800, { type: 'agent.message', case_id, agent: 'logistics', text: 'Item was returned and refunded in full on 2026-09-22. The chargeback is a second recovery on the same charge. @critic', mentions: ['critic'] }],
    [8600, { type: 'evidence.attached', case_id, agent: 'forensics', evidence: { id: 'ev_claim', family: 'claim_artifacts', label: '"My agent did it" statement', detail: 'Cardholder statement attributes the purchase to an AI assistant. Under UETA and Meta\'s Muse terms the user is responsible for transactions their agent makes. Return was requested through the same agent two days after delivery.', severity: 'suspicious', weight: 0.2, node_ids: ['dp_doubledip'] } }],
    [9000, { type: 'agent.message', case_id, agent: 'forensics', text: 'No photos to assess. The statement itself is the artifact: the agent that "wasn\'t authorized" also filed the return. @critic', mentions: ['critic'] }],
    [9800, { type: 'agent.status', case_id, agent: 'critic', status: 'thinking', detail: 'weighing 6 evidence items' }],
    [11200, { type: 'verdict', case_id, tier: 'decline', confidence: 0.92, score: 0.86, rationale: 'Double recovery: a full refund was already issued for this charge on carrier scan, and the item was received. The purchase session was an undeclared agent on the customer\'s own account, the return was filed through the same agent, and delivery is proven. Decline the second refund and represent the dispute.', policy_citation: 'Return policy v2026-08-01: refunds are issued once per item, after inspection unless noted.', evidence_ids: ['ev_fp', 'ev_egress', 'ev_hist', 'ev_delivery', 'ev_refund', 'ev_claim'] }],
    [12200, { type: 'dispute.routing', case_id, dispute_id: 'dp_doubledip', decision: 'representment', rationale: 'Refund-and-close would pay the customer twice. Evidence of prior refund plus delivery proof is strong even without CE 3.0 device matching. One VAMP item either way; representment protects $289.', vamp: { ratio_before: 0.0133, ratio_after: 0.0136, threshold: 0.015, headroom_items: 6 }, expected_recovery: 289 }],
    [13400, { type: 'stripe.evidence_staged', case_id, dispute_id: 'dp_doubledip', due_by: '2026-10-08T16:00:00.000Z', submitted: false, evidence: { product_description: 'Summit Down Parka M Spruce x1', refund_policy_disclosure: 'Return policy v2026-08-01 accepted at checkout 2026-09-18.', refund_refusal_explanation: 'A full refund of $289.00 was already issued on 2026-09-22 against the returned item (inbound weight 1,010 g, expected 980 g).', shipping_carrier: 'FedEx', shipping_tracking_number: '1Z…', shipping_documentation: 'Carrier delivery scan to order address.', uncategorized_text: 'Order placed by an automated shopping agent operating on the cardholder\'s own account (undeclared agent signals attached). The return for this order was requested through the same agent.' } }],
    [14600, { type: 'agent.message', case_id, agent: 'critic', text: 'Verdict: decline second refund, represent dp_doubledip. Evidence package staged for merchant review, due 2026-10-08.', mentions: [] }],
    [15200, { type: 'case.closed', case_id, outcome: 'representment staged; awaiting merchant approval' }],
  ]
  return seq.map(([at_ms, event]) => ({ at_ms, event }))
}

export const REPLAYS: Record<string, () => TimedEvent[]> = { doubledip: doubleDipReplay }
